### ISSUE TITLE
Migrate TI Process

### ISSUE THREAD

**Issue by CubewisePacific** [Cubewise-Pacific/PCC#2]

**Comment by CubewisePacific** [comment]
**Requirements:**
- [ ] Use PCC TM1 objects and consistent coding
- [ ] Copy TI process from one TM1 instance to another

**Sub-Tasks:**
- [ ] Write python script called turbointegrator_process_sync and put it in the metadata_sync folder
- [ ] Test and include error trapping (then re-test and update error trapping etc)
- [ ] Create executable
- [ ] Update documentation (including any TM1 objects, config settings, what it does/does not do, future enhancements, etc.)
- [ ] Review with Andrew
