### ISSUE TITLE
TM1 Transaction Log in a TM1 cube?

### ISSUE THREAD

**Issue by CubewisePacific** [Cubewise-Pacific/PCC#3]

**Comment by CubewisePacific** [comment]
**Requirements:**
- [ ] Use PCC TM1 objects and consistent coding
- [ ] Create TM1 Transaction Log cube (use Inari as basis)
- [ ] Review requirements with Andrew

**Sub-Tasks:**
- [ ] Write python script called tm1_transaction logs and put it in the montoring_reporting folder
- [ ] Test and include error trapping (then re-test and update error trapping etc)
- [ ] Create executable
- [ ] Update documentation (including any TM1 objects, config settings, what it does/does not do, future enhancements, etc.)
- [ ] Review with Andrew
