### ISSUE TITLE
Email Notification

### ISSUE THREAD

**Issue by CubewisePacific** [Cubewise-Pacific/PCC#8]
**Requirements:**
- [ ] Use PCC TM1 objects and consistent coding
- [ ] Keep it simple and modular

**Sub-Tasks:**
- [ ] Write python script called send_email and put it in the notifications folder
- [ ] Test and include error trapping (then re-test and update error trapping etc)
- [ ] Create executable
- [ ] Update documentation (including any TM1 objects, config settings, what it does/does not do, future enhancements, etc.)
- [ ] Review with Andrew
